# Generated by Django 5.2.1 on 2025-05-25 13:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="conteudo",
        ),
        migrations.RemoveField(
            model_name="post",
            name="data_criacao",
        ),
        migrations.RemoveField(
            model_name="post",
            name="titulo",
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(default="Conteúdo não informado"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="publish",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="post-antigo", max_length=250, unique_for_date="publish"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("draft", "Rascunho"), ("published", "Publicado")],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="Título padrão", max_length=250),
            preserve_default=False,
        ),
    ]
